{% set name = "unicorn-binance-websocket-api" %}
{% set version = "2.15.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unicorn_binance_websocket_api-{{ version }}.tar.gz
  sha256: 6a61db60dd73ea95d8f10d3ca6bb98609847dcef2cf31b46264b4b7a4e3d0e90

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - mypy
  run:
    - python
    - cython
    - colorama
    - requests >=2.31.0
    - websocket-client
    - websockets >=14.0
    - orjson
    - psutil
    - pysocks
    - unicorn-fy >=0.17.2
    - unicorn-binance-rest-api >=2.12.0
    - typing_extensions

test:
  imports:
    - unicorn_binance_websocket_api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api
  summary: An unofficial Python API to use the Binance Websocket APIs.
  description: |
    An unofficial Python API to use the Binance Websocket APIs (com+testnet,
    com-margin+testnet, com-isolated_margin+testnet, com-futures+testnet,
    us, tr) in an easy, fast, flexible, robust and fully-featured way.
    Part of the UNICORN Binance Suite.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api
  doc_url: https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api

extra:
  recipe-maintainers:
    - oliver-zehentleitner
